/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaCliente;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Josue
 */
public class FrmAgregar extends javax.swing.JFrame {

    /**
     * Creates new form FrmAgregar
     */
    public FrmAgregar() {
        initComponents();
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Logo.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DiaGrupo = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblMateria = new javax.swing.JLabel();
        lblEntrega = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        jNomTarea = new javax.swing.JTextField();
        jHorasD = new javax.swing.JTextField();
        lblHora1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jHoraAct = new javax.swing.JComboBox<>();
        Lunes = new javax.swing.JRadioButton();
        Martes = new javax.swing.JRadioButton();
        Miercoles = new javax.swing.JRadioButton();
        Jueves = new javax.swing.JRadioButton();
        Viernes = new javax.swing.JRadioButton();
        Sabado = new javax.swing.JRadioButton();
        Domingo = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        Regresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitulo.setText("Agregar nueva tarea");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNombre.setText("Ingrese la hora de entrega:");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        lblMateria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMateria.setText("Ingrese el nombre de la tarea:");
        getContentPane().add(lblMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        lblEntrega.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEntrega.setText("Selecciones el dia de entrega:");
        getContentPane().add(lblEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        lblHora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHora.setText("realizar la tarea:");
        getContentPane().add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));
        getContentPane().add(jNomTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 250, -1));

        jHorasD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHorasDActionPerformed(evt);
            }
        });
        getContentPane().add(jHorasD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 250, -1));

        lblHora1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHora1.setText("Ingrese las horas  a conciderar para");
        getContentPane().add(lblHora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        jHoraAct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        jHoraAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHoraActActionPerformed(evt);
            }
        });
        getContentPane().add(jHoraAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        DiaGrupo.add(Lunes);
        Lunes.setText("Lunes");
        getContentPane().add(Lunes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 60, -1));

        DiaGrupo.add(Martes);
        Martes.setText("Martes");
        getContentPane().add(Martes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        DiaGrupo.add(Miercoles);
        Miercoles.setText("Miercoles");
        getContentPane().add(Miercoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 70, -1));

        DiaGrupo.add(Jueves);
        Jueves.setText("Jueves");
        getContentPane().add(Jueves, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 70, -1));

        DiaGrupo.add(Viernes);
        Viernes.setText("Viernes");
        getContentPane().add(Viernes, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        DiaGrupo.add(Sabado);
        Sabado.setText("Sabado");
        getContentPane().add(Sabado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        DiaGrupo.add(Domingo);
        Domingo.setText("Domingo");
        getContentPane().add(Domingo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 70, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText(":00 hrs");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoInicio.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jHorasDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHorasDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHorasDActionPerformed

    private void jHoraActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHoraActActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHoraActActionPerformed

    FrmMenuPrincipal tab = new FrmMenuPrincipal();
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int horD = 0;
        
        int horAct = Integer.parseInt(jHoraAct.getSelectedItem().toString());
        horD = Integer.parseInt(jHorasD.getText());
        int actI;
        String nomact = jNomTarea.getText();
        
        
        if(horD == 0 || nomact.equals("")){
            
            
            JOptionPane.showMessageDialog(null, "ALGUNOS CAMPOS ESTAN VACIOS");
            
        }else{
        
        if(Lunes.isSelected()){
            actI = 1;

            tab.AgregarTareas(horAct, actI, horD, nomact);
        }
        
        if(Martes.isSelected()){
            actI = 2;
            
            tab.AgregarTareas(horAct, actI, horD, nomact);
        }
        
        if(Miercoles.isSelected()){
            actI = 3;
            
            tab.AgregarTareas(horAct, actI, horD, nomact);
        }
        
        if(Jueves.isSelected()){
            actI = 4;
            
            tab.AgregarTareas(horAct, actI, horD, nomact);
        }
        
        if(Viernes.isSelected()){
            actI = 5;
            
            tab.AgregarTareas(horAct, actI, horD, nomact);
        }
        
        if(Sabado.isSelected()){
            actI = 6;
            
            tab.AgregarTareas(horAct, actI, horD, nomact);
        }
        
        if(Domingo.isSelected()){
            actI = 7;
            
            tab.AgregarTareas(horAct, actI, horD, nomact);
        }
       
        tab.setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        tab.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup DiaGrupo;
    private javax.swing.JRadioButton Domingo;
    private javax.swing.JRadioButton Jueves;
    private javax.swing.JRadioButton Lunes;
    private javax.swing.JRadioButton Martes;
    private javax.swing.JRadioButton Miercoles;
    private javax.swing.JButton Regresar;
    private javax.swing.JRadioButton Sabado;
    private javax.swing.JRadioButton Viernes;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jHoraAct;
    private javax.swing.JTextField jHorasD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jNomTarea;
    private javax.swing.JLabel lblEntrega;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblHora1;
    private javax.swing.JLabel lblMateria;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
