/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaCliente;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Josue
 */
public class FrmFormulario extends javax.swing.JFrame {

    /**
     * Creates new form FrmFormulario
     */
    int horasEscuela;
    int horasact;
    int horasEstudio;
    
    public FrmFormulario() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Logo.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblPrimera = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblSegunda = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        lblTercera = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitulo.setText("FORMULARIO");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        lblPrimera.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPrimera.setText("Ingresa las horas que asiste a la escuela:");
        getContentPane().add(lblPrimera, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 47, -1, -1));

        lblSegunda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSegunda.setText("Ingrese las horas de todas sus actividades:");
        getContentPane().add(lblSegunda, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 293, 29));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", " " }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 96, -1, -1));

        lblTercera.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTercera.setText("Ingrese las horas de estudio que realiza:");
        getContentPane().add(lblTercera, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 151, -1, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoInicio.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        horasEscuela = Integer.parseInt((String) jComboBox1.getSelectedItem());
        horasact = Integer.parseInt((String) jComboBox2.getSelectedItem());
        horasEstudio = Integer.parseInt((String) jComboBox3.getSelectedItem());
        
        
        
        /*for (int i = 0; i < ; i++) {
            
        }
        jComboBox1.add(horasEscuela);*/
        
        JOptionPane.showMessageDialog(this, "Se guardo con exito");
        FrmMenuPrincipal abrir = new FrmMenuPrincipal(); 
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblPrimera;
    private javax.swing.JLabel lblSegunda;
    private javax.swing.JLabel lblTercera;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
