/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lookand;

import javax.swing.JOptionPane;

/**
 *
 * @author Josue
 */
public class Registrar extends javax.swing.JFrame {

    /**
     * Creates new form Registrar
     */

    public Registrar() {
        initComponents();
        this.setLocationRelativeTo(this);
    }       
        Usuario objeto = new Usuario();ControlarPersona obj = new ControlarPersona();
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblRegistroUsuario = new javax.swing.JLabel();
        lblRegistroPassword = new javax.swing.JLabel();
        lblRegistrarConfirmePassword = new javax.swing.JLabel();
        txtRegistroUsuario = new javax.swing.JTextField();
        txtRegistroConfirmePassword = new javax.swing.JPasswordField();
        btnRegistrarse = new javax.swing.JButton();
        txtRegistroPassword = new javax.swing.JTextField();
        btnIniciar = new javax.swing.JButton();
        lblFondoRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/images.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel3.setText("REGISTRO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        lblRegistroUsuario.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblRegistroUsuario.setText("Crea un nuevo nombre de usuario:");
        getContentPane().add(lblRegistroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        lblRegistroPassword.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblRegistroPassword.setText("Crea una nueva contraseña:");
        getContentPane().add(lblRegistroPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, 20));

        lblRegistrarConfirmePassword.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblRegistrarConfirmePassword.setText("Confirme la contraseña:");
        getContentPane().add(lblRegistrarConfirmePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, -1, -1));
        getContentPane().add(txtRegistroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 330, -1));
        getContentPane().add(txtRegistroConfirmePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 330, -1));

        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, -1, -1));
        getContentPane().add(txtRegistroPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 330, -1));

        btnIniciar.setText("Iniciar Sesion");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, -1, -1));

        lblFondoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoInicio.jpg"))); // NOI18N
        getContentPane().add(lblFondoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        String nombre = txtRegistroUsuario.getText();
        String password = txtRegistroPassword.getText();
        String confirme = txtRegistroConfirmePassword.getText();
        
        if(password.equals("") || nombre.equals("") || confirme.equals("")){
            JOptionPane.showMessageDialog(null, "CAMPOS VACIOS.");
        }else{
            if(password.equals(confirme)){
        objeto = new Usuario(nombre,password);
        obj.agregar(objeto);
        JOptionPane.showMessageDialog(null, "USUARIO RESGISTRADO EXITOSAMENTE.");
        }else{
            JOptionPane.showMessageDialog(null, "SE HAN INGRESADO DIFERENTES CONTRASEÑAS.");
        }
        }
        
        
        
        
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        IniciarSesion abrir = new IniciarSesion();
        abrir.setVisible(true);
        this.dispose();
        Registrar cerrar = new Registrar();
        cerrar.setVisible(false);
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblFondoRegistro;
    private javax.swing.JLabel lblRegistrarConfirmePassword;
    private javax.swing.JLabel lblRegistroPassword;
    private javax.swing.JLabel lblRegistroUsuario;
    private javax.swing.JPasswordField txtRegistroConfirmePassword;
    private javax.swing.JTextField txtRegistroPassword;
    private javax.swing.JTextField txtRegistroUsuario;
    // End of variables declaration//GEN-END:variables
}
