/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa;

import javax.swing.JOptionPane;

/**
 *
 * @author Josue
 */
public class FrmMenuRegistrarse extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuRegistrarse
     */
    public FrmMenuRegistrarse() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblnombreusuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        txtRegistrousuario = new javax.swing.JTextField();
        btnregistarse = new javax.swing.JButton();
        btnregistroIniciarsesión = new javax.swing.JButton();
        txtRegistrocontraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitulo.setText("REGISTRARSE");

        lblnombreusuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblnombreusuario.setText("Ingrese un nombre de usuario:");

        lblContraseña.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblContraseña.setText("Ingrese una contraseña:");

        btnregistarse.setText("Registrarse");
        btnregistarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistarseActionPerformed(evt);
            }
        });

        btnregistroIniciarsesión.setText("Iniciar sesión");
        btnregistroIniciarsesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistroIniciarsesiónActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(177, 177, 177))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblContraseña))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblnombreusuario)))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRegistrousuario)
                    .addComponent(txtRegistrocontraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(btnregistarse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(btnregistroIniciarsesión)
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombreusuario)
                    .addComponent(txtRegistrousuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContraseña)
                    .addComponent(txtRegistrocontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnregistarse)
                    .addComponent(btnregistroIniciarsesión))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregistarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistarseActionPerformed
        // TODO add your handling code here:
        String usuario = txtRegistrousuario.getText();
        String contraseña = txtRegistrocontraseña.getText();
        Usuario obj = new Usuario();
        if(Usuario.verificarUsuario(usuario)==-1){
            obj.setUsername(usuario);
        obj.setContraseña(contraseña);
        Listausuario.agregar(obj);
            JOptionPane.showMessageDialog(this, "EL REGISTRO HA SIDO UN ÉXITO ROTUNDO, VENMGAN ESOS CORRIDOS.");
        }else{
            JOptionPane.showMessageDialog(this, "EL USUARIO, YA ESTA EN USO, PANITA");
        }
        
    }//GEN-LAST:event_btnregistarseActionPerformed

    private void btnregistroIniciarsesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistroIniciarsesiónActionPerformed
        // TODO add your handling code here:
        FrmLoggeo abrir = new FrmLoggeo();
        abrir.setVisible(true);
        
        FrmMenuRegistrarse cerrar = new FrmMenuRegistrarse();
        cerrar.setVisible(false);
    }//GEN-LAST:event_btnregistroIniciarsesiónActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregistarse;
    private javax.swing.JButton btnregistroIniciarsesión;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblnombreusuario;
    private javax.swing.JPasswordField txtRegistrocontraseña;
    private javax.swing.JTextField txtRegistrousuario;
    // End of variables declaration//GEN-END:variables
}
